name:                ginger
version:             1.0.0.0
github:              "VladSaioc/ginger"
license:             BSD3
author:              "Georgian-Vlad Saioc"
maintainer:          "gvsaioc@cs.au.dk"
copyright:           "2023 Georgian-Vlad Saioc"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/VladSaioc/ginger#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal
- array
- pretty-simple
- clock
- containers
- text
- directory
- formatting
- process
- regex-tdfa
- split
- transformers
- union-find

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ginger-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ginger

default-extensions:
  - BangPatterns
  - DeriveAnyClass
  - TupleSections
  - TypeOperators
  - NamedFieldPuns
  - LambdaCase
  - StandaloneDeriving
  - ImportQualifiedPost
  - PostfixOperators
  - PatternSynonyms

tests:
  ginger-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ginger
